### ISSUE TITLE
[Feature Request] Add SIP MESSAGE capabilities

### ISSUE THREAD

**Issue by amessina** [collecttix/ctxSip#12]
Consider implementing support for sending/receiving/displaying SIP MESSAGEs, a useful feature addition.

**Comment by bmac901** [comment]
That is a out of the scope of this project.  SIP.js has this functionality.  If you want to implement this, I will consider it.

**Comment by amessina** [comment]
@bmac901 Thank you for your reply.  I'll close this for now and update if I am able to add the feature.
