### ISSUE TITLE
Problem when working with meteor and sip.js installed as node module

### ISSUE THREAD

**Issue by damirius** [collecttix/ctxSip#15]
Can you tell me if you tested your phone app with sip.js installed as node module in meteor?
I'm encountering some problems here:
`modules.js?hash=32b0f2f…:15998 Uncaught (in promise) TypeError: Cannot read property 'close' of undefined(…)`
which is thrown by this line:
`exports.clearInterval = function(timeout) { timeout.close(); };  `

That line in question is part of meteor-node-stubs, which are meteor essentials installed as node module, more specifically this one which is part of that: https://www.npmjs.com/package/timers-browserify

So do you think you can help me or should I ask on sip.js git page?

**Comment by bmac901** [comment]
I have not tested it in meteor.  I suspect though that you have a name conflict clearInterval() is a native JS function.  The timers-browserfy exports a modified of these.

As a fix, in app.js,  replace:
- `setInterval` with `window.setInterval`
- `clearInterval` with `window.clearInterval`

If it works, submit a PR or let me know and I'll fix it.
