### ISSUE TITLE
Https (With Open SSL,TLS Certificates) Configuration Guide Required For Chrome

### ISSUE THREAD

**Issue by mubashir01** [collecttix/ctxSip#16]
We require ctxSip Phone with Asp.net library on chrome browser, we have successfully tested on localhost (IIS ) with ws  using following configuration,
SipID:4000
SipPwd:4000
ws URL:
ws://10.197.0.186:8088/ws

Sip Realm:
10.197.0.186

Where 10.197.0.186 is our FreePBX (Asterisk v13)  IP:

getUserMedia failed: NavigatorUserMediaErrorconstraintName: ""message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)."name: "PermissionDeniedError"__proto__: NavigatorUserMediaErrorgetUserMediaFailure @ app.js:193

![phone_error](https://cloud.githubusercontent.com/assets/16221819/20840173/20e1c17e-b8d1-11e6-90a0-d2fd6904a194.png)

**Comment by bmac901** [comment]
SSL is required for connections other than localhost.  You will need to setup certs on either your PBX, or proxy the requests with something like nginix or haproxy in front of it. 

This is an important security feature in browsers.  It protects against script insertion from attackers.

Note the the websocket connection address with then should be:
__wss__://yourhost.example.com:8088/ws

Certificates need a hostname to work.
