### ISSUE TITLE
Auto Answer a call

### ISSUE THREAD

**Issue by saqlainnawaz** [collecttix/ctxSip#17]
I am trying to integrate it with my asterisk telephony engine and I was wondering if there is a way to set it to auto answer? 
If there is, please let me know.

**Comment by srivishalsangepu** [comment]
Hi @saqlainnawaz sir,
Have you completely solved the auto answer issue, please let me know if you have done with it.
Thanks & regards 
srivishal

**Comment by saqlainnawaz** [comment]
@srivishalsangepu Yes. I did that a long time ago

**Comment by srivishalsangepu** [comment]
@saqlainnawaz can you please tell me how to achieve it.
Thanks and Regards 
srivishal

**Comment by saqlainnawaz** [comment]
@srivishalsangepu I did following. 

Write a new function to answer the call.

```
autoanswer :  function(newS) {
        		ctxSip.phoneCallButtonPressed(newS.ctxid);
        },
```
And call this function in invite. 

```
 ctxSip.phone.on('invite', function (incomingSession) {

        var s = incomingSession;
		
        s.direction = 'incoming';
        ctxSip.newSession(s);
        writeS(s);
        ctxSip.autoanswer(s);
       
    });
```

**Comment by saqlainnawaz** [comment]
@srivishalsangepu You are welcome.

**Comment by srivishalsangepu** [comment]
hi @saqlainnawaz sir, have you tried conference calls in ctxsip.

**Comment by saqlainnawaz** [comment]
@srivishalsangepu I haven't tried yet but it should be easy. Store the session value in some variable and just invite the channel to that session for conferencing.

**Comment by 1zain-haider1** [comment]
hi ...i am using ctxphone along sip.js outgoing is working fine but incoming doesn't seem to be working .... mycalls can't land on the phone is there any thing em missing.. em super new to this ..i just find above something related so i just asked
