### ISSUE TITLE
error  while outging call made

### ISSUE THREAD

**Issue by suhani2911** [collecttix/ctxSip#20]
Rejecting secure audio stream without encryption details: audio 58843 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126

**Comment by bmac901** [comment]
Sounds like a server configuration issue, what server software is it trying to connect to?

**Comment by tedd77** [comment]
You need to make sure your certificates are authentic, this seems to come due to self signed certificates where webrtc do not like anymore.
