### ISSUE TITLE
backend

### ISSUE THREAD

**Issue by mizutechvoip** [collecttix/ctxSip#21]
Is it possible to use this as a frontend for [this web sip engine](https://www.mizu-voip.com/Software/WebPhone.aspx)? I have a customer who likes the ctxSip solution very much, but needs also native SIP/RTP support (not just WebRTC) and for this the above mizu engine would be suitable. Other users might also benefit from this integration.
(I am the author of this webphone library)

**Comment by bmac901** [comment]
Thanks for checking out my project.  I am glad you like the UI.  Please feel free to use as much as my code as you like.  It is free and open source.  Patches are welcome.

**Comment by mizutechvoip** [comment]
Thank you, we are going to check this possibility for the next customer who will ask similar thing as for the current one we have implemented a separate GUI.
