### ISSUE TITLE
CTXSip incoming call multiple sessions created 

### ISSUE THREAD

**Issue by shineedcosta** [collecttix/ctxSip#26]
I have multiple asterisk extensions ,few mapped to 3cx and one mapped to ctxsip. A DID number e.g. 026001000 is mapped to a queue having all the extensions . So when i dial DID number from mobile, the call is forwarded to the queue , it lands on registered extensions .Issue i am facing is in case the call lands on CTXsip it creates multiple sessions for the same incoming call and i am unable to receive the call when i click on phone icon.

**Comment by bmac901** [comment]
Session handling has been improved in newer versions of SIP.js.  I do plan to update it in the near future.

**Comment by 1zain-haider1** [comment]
hi ...i am using ctxphone along sip.js  outgoing is working fine but incoming doesn't seem to be working .... mycalls can't land on the phone is there any thing em  missing.. em super new to this ..i just find above something related so i just asked

**Comment by edsel77** [comment]
still encountering this error on the latest version of sip.js@0.15.6
