### ISSUE TITLE
Sip proxy

### ISSUE THREAD

**Issue by Mancy** [collecttix/ctxSip#5]
Hello,
is there anyway to add sip proxy to the configuration?
for example in sipML5 there is proxy server 'ns313841.ovh.net'
can be found here 
https://github.com/DoubangoTelecom/sipml5/search?utf8=%E2%9C%93&q=ns313841.ovh.net
it's useful to fix audio problems 

please advice

Thanks

**Comment by bmac901** [comment]
sipML5 is a different product that sip.js. I don't have a proxy setup to test, but try this...

In scripts/app.js, edit the config object to add a `registrarServer` property.

```
config : {
            password        : user.Pass,
            displayName     : user.Display,
            uri             : 'sip:'+user.User+'@'+user.Realm,
            wsServers       : user.WSServer,
            registerExpires : 30,
            traceSip        : true,
           
            // 
            registrarServer: 'sip:registrar.mydomain.com'
            log             : {
                level : 3,
            }
        },
       ...
```

If it works, submit a PR or let me know and I will add it.

**Comment by Mancy** [comment]
i think the the outbound proxy could be set by using the following config option
usePreloadedRoute: true
but then, line 3906 in sip.js 
this.setHeader('route', ua.transport.server.sip_uri);
need to be fixed to accommodate this config option
