### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by mizutechvoip** [collecttix/ctxSip#7]
I am trying to integrate it with the our [web sip client](https://www.mizu-voip.com/Software/WebPhone.aspx) engines, however for NS engine I always get "undefined plhandler" errors.
Do you have any suggestion on how to add other engines to your user interface apart from WebRTC? 
Otherwise it is a nice project and it would be fine if people can change the underlying SIP.js engine.

**Comment by bmac901** [comment]
Thanks for checking out the project.  Unfortunately, it is pretty tightly integrated to SIP.js.

I took a quick glance at the mizutech client and it looks like a great project.  I really do not know enough about it (or your code) to help troubleshoot your issue. But, you are welcome to use any part of my interface as it is MIT Licensed.

**Comment by mizutechvoip** [comment]
Thank you. I will try this again a bit later.
