### ISSUE TITLE
Issue in Chrome App

### ISSUE THREAD

**Issue by wiii** [collecttix/ctxSip#8]
Hello , excellent client implementation in jQuery to sip.js.

Since a few days ago, I've been trying to use it from a chrome app, but I have not succeeded.
Initially I thought it was this, https://github.com/onsip/SIP.js/issues/163 but still does not work, although this state ready softphone calls do not go.

You could give me a hand with this, if they want gives me your email and I send files chrome app is only for charging and test it.

Note: I have already discussed all traces of onload and beforeOnLoad within app.js

**Comment by bmac901** [comment]
I thought about this too but:

http://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

Chrome Apps are about to go away...
